dist: xenial
language: python
sudo: false
cache: pip
branches:
  only:
    - master

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy2.7-6.0
  - pypy3.5-6.0

matrix:
  include:
    - python: 3.7
      env: TOXENV=flake8

install:
  - pip install tox-travis tox-docker
script:
  - tox
after_success:
  - pip install coveralls
  - coveralls
